version: '3'
services: 
    node:
        build:
            context: ./app
            dockerfile: "Dockerfile"
        image: angular-node-express
        container_name: angular-node-express
        ports:
            - 3000:3000
        command: [sh, -c, npm install && npm start]
    